### ISSUE TITLE
插件卸载之后没有将对应的bean移除，导致重新加载插件时候会报错。

### ISSUE THREAD

**Issue by VictorShadow89** [stateIs0/exp#2]
建议在cn.think.in.java.open.exp.adapter.springboot2.SpringBootObjectStore类中加上，卸载插件的时候，顺便将对应的bean移除。
  /**
     * bean移除
     * @param beanName
     */
    public void unregisterBean(String beanName){
        log.info("unregisterBean->beanName:{}",beanName);
        beanDefinitionRegistry.removeBeanDefinition(beanName);
    }

private void unRegisterCallback(Class<?> aClass, String pluginId) {
        String name = UniqueNameUtil.getName(aClass, pluginId);
        RestUrlScanComponent urlComponent = cache.get(name);
        if (urlComponent != null) {
            **unregisterBean(name);**
            urlComponent.unRegister();
            cache.remove(name);
        }
    }

**Comment by stateIs0** [comment]
@VictorShadow89 已修复，请 pull 最新代码

**Comment by VictorShadow89** [comment]
> @VictorShadow89 已修复，请 pull 最新代码

嗯嗯，看到了。
