### ISSUE TITLE
SimpleJavaAppMain的main方法启动报错。

### ISSUE THREAD

**Issue by liushaoCode** [stateIs0/exp#31]
expAppContext = Bootstrap.bootstrap("/Users/liushao/Downloads/exp-main/exp-plugins/","/Users/liushao/Downloads/exp-main/example/simple-java-app/");

启动后报错如下：
14:48:36.491 [main] INFO cn.think.in.java.open.exp.core.impl.Bootstrap - 准备安装插件, 压缩包路径: /Users/liushao/Downloads/exp-main/exp-plugins/example-plugin-b-v2-1.0-SNAPSHOT-1.0-SNAPSHOT.zip
14:48:36.540 [main] INFO cn.think.in.java.open.exp.classloader.support.ClassLoaderFinder - dir /Users/liushao/Downloads/exp-main/example/simple-java-app//cn.think.in.java.open.exp.example.b_2.0.0 isParentMode = parent-first
14:49:04.279 [main] ERROR cn.think.in.java.open.exp.core.impl.Bootstrap - java.lang.NoClassDefFoundError: Lorg/mybatis/spring/SqlSessionTemplate; ---->>>> /Users/liushao/Downloads/exp-main/exp-plugins/example-plugin-b-v2-1.0-SNAPSHOT-1.0-SNAPSHOT.zip
java.lang.RuntimeException: java.lang.NoClassDefFoundError: Lorg/mybatis/spring/SqlSessionTemplate;

**Comment by stateIs0** [comment]
fix
