### ISSUE TITLE
获取主应用属性

### ISSUE THREAD

**Issue by 13619307257** [stateIs0/exp#4]
您好，想问一下，如果想获取主应用的某个对象，有办法获取吗？

**Comment by stateIs0** [comment]
@13619307257 直接 spring 注入就可以了

**Comment by 13619307257** [comment]
子应用想获取呢，比如：子应用想获取主应用的某个对象或者某个接口。

**Comment by stateIs0** [comment]
@13619307257 就和普通的 spring 写法一样， @Resource 注入【主应用的某个对象或者某个接口】就可以了

**Comment by 13619307257** [comment]
好的，谢了，请教一下，要访问子应用的RestApi接口，怎么访问，按什么规则?

**Comment by stateIs0** [comment]
@13619307257 按照 spring 正常规则访问就行
