### ISSUE TITLE
兄弟，用eclipse导入项目报错

### ISSUE THREAD

**Issue by TeddyLav** [stateIs0/exp#5]
如图所示：
![error](https://github.com/stateIs0/exp/assets/106192505/325f81e0-5914-45e3-a66b-6151cb49ada8)

**Comment by stateIs0** [comment]
把 maven 插件 install 下 @TeddyLav

**Comment by TeddyLav** [comment]
这个具体要怎么运行呢？我直接在example下面随便找一个main函数，run application 报错

**Comment by stateIs0** [comment]
@TeddyLav 报什么错贴一下，eclipse  我不太熟悉，一般用 idea

**Comment by TeddyLav** [comment]
我每个项目都mvn install了一遍，基本能跑了，但是有点不明白
我运行了example下面的cn.think.in.java.open.exp.adapter.springboot2.MainBoot2，理论上应该只把BaseController加载起来，但是不知道怎么调用到cn.think.in.java.open.exp.core.impl.Bootstrap 开始扫描加载jar和zip包的？

**Comment by stateIs0** [comment]
@TeddyLav debug 看看呢，好好感受下

**Comment by stateIs0** [comment]
@TeddyLav extension.properties 用来扩展的，后期会用到，比如校验；

插件的日志现在是逻辑隔离的，mdc 里有保存插件 id，可以过滤，目前似乎没必要物理隔离日志。
